services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/storage
        networks:
            - app-network
        entrypoint: |
            /bin/bash -c "
                php artisan key:generate;
                apache2-foreground"

networks:
    app-network:
        driver: bridge
